Feature/stale time
serverless-seoul/cache pull request #37
Opened 2021-01-12 04:43 UTC by mooyoul

#### Is it a breaking change?: Yes, Requires Node.js 12+

### Why did you make these changes?

Complex fetcher cache control is required for keeping high availability

### What's changed in these changes?

- Added `staleTime` option to the Fetcher#fetch method
- Added benchmark scripts for further changes
- Changed branding

### What do you especially want to get reviewed?

N/A

### Is there any other comments that every teammate should know?

N/A

### Submission Type

* [x] Bugfix
* [x] New Feature

### All Submissions

* [ ] Have you added an explanation of what your changes?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you checked potential side effects that could make bad impacts to other services?

2021-01-12 06:52 UTC, breath103 requested changes
staleTime 동작 방식에 대해서 테스트 추가해서 머지해주세요

2021-01-12 06:52 UTC, breath103 commented on src/drivers/redis_cluster.ts
> +  public client: IORedis.Cluster;
public readonly

2021-01-12 06:52 UTC, breath103 commented on src/fetcher.ts
> +  public async fetch<Result>(key: string, lifetime: number | Lifetime, fetcher: () => Promise<Result>): Promise<Result> {
staleTime에 대해서는 테스트가 없네?;

2021-01-13 02:16 UTC, breath103 approved these changes
이거만 확인해서 올려서 테스트 해보시면 됨

2021-01-13 02:16 UTC, breath103 commented on src/drivers/redis.ts
> +          hash[key] = val as any;
val as Result | undefined 아니고요?

2021-01-13 09:22 UTC, mooyoul commented on src/drivers/redis.ts
> +          hash[key] = val as any;
이게 아마 옛날에 썼던 코드인거 같은데, string 저장할때 json stringify 안하고 그냥 저장한적이 있어서 fallback으로 남겨놨던거 같거든요? 이젠 이 경우엔 undefined로 처리하게 하는게 맞는것 같은데 어떻게 하는게 좋을까요

2021-01-14 02:26 UTC, breath103 commented on src/drivers/redis.ts
> +          hash[key] = val as any;
아 음............ undefined로 하시죠? 이게 문제될만한 상황 자체가 거의 없긴 할겁니다 (대부분 object를 저장하지 뭐 단순 string을 저장하는 경우는 드무니까요)

2021-01-14 09:26 UTC, merged